platform: "kubernetes"
operator:
  image: ""
oneagent:
  name: "oneagent"
  apiUrl: ""
  image: ""
  args:
    - --set-app-log-content-access=true
  env:
     - name: ONEAGENT_ENABLE_VOLUME_STORAGE      
       value: "true"
  nodeSelector: {}
  labels: {}
  skipCertCheck: true
  disableAgentUpdate: false
  enableIstio: false
  dnsPolicy: ""
  resources: {}
  waitReadySeconds: null
  priorityClassName: ""
  serviceAccountName: ""
  proxy: ""
  trustedCAs: ""
secret:
  apiToken: "token"
  paasToken: "pass"