apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
type: Opaque
data:
  ENCRYPTION_KEY: {{ default "MISSING" .Values.secrets.ENCRYPTION_KEY | b64enc | quote }}
 