# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

 

replicaCount: 1

 

image:
  repository: 
  pullPolicy: Always
  # Overrides the image tag whose default is the chart latest.
  tag: latest

 

imagePullSecrets:
  - name: acr-pull-secret

 

# This values are set by the CI/CD pipeline after retrieving secrets from KeyVault
secrets:
  ENCRYPTION_KEY:

 

env:
  AUTH_CLIENT_ID: 
  AUTH_CLIENT_SECRET: 
  AUTH_DEFAULT_TARGET_URI: 
  AUTH_IDENTITY_SERVER_URI: 

 

  DATABASE_URL: 
  DATABASE_USERNAME: 
  DATABASE_PASSWORD: 

 

  PARAMS: test

 

  LDAP_BASE: 
  LDAP_ENDPOINT: 
  LDAP_USERNAME: 
  LDAP_PASSWORD: 
  
  SPRING_PROFILES_ACTIVE: cloud
    
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

 

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

 

service:
  type: ClusterIP
  port: 80

 

nodeSelector: {}

 

tolerations: []

 

affinity: {}